### ISSUE TITLE
Failed to execute (OptimizeRasters)

### ISSUE THREAD

**Issue by DouglasBradley** [Esri/OptimizeRasters#98]
I am getting the below error when trying to execute any operation within the OptimizeRasters function. It occurs when running from the toolbox in Pro or using the command line. I am running the tool with the provided base configuration files. Any guidance will be greatly appreciated. 

"Start Time: Wednesday, 22 January 2020 14:17:21
Running script OptimizeRasters...
 Traceback (most recent call last):
  File "<string>", line 955, in execute
  File "C:\Image_Mgmt_Workflows\OptimizeRasters-master\OptimizeRasters.py", line 4886, in init
    self._base._m_log.isGPRun = self.postMessagesToArcGIS
AttributeError: 'NoneType' object has no attribute 'isGPRun'
 Failed to execute (OptimizeRasters)."

**Comment by DouglasBradley** [comment]
I forgot to mention that this error occurs when running in python 3 and the same setup works fine with python 2.7.

**Comment by abhiataero** [comment]
@DouglasBradley what is the version of pro used also can you give the command line that you are using

**Comment by DouglasBradley** [comment]
> @DouglasBradley what is the version of pro used also can you give the command line that you are using

I am running Pro 2.4.3 the cmd line I am running is:
C:\Users\DouglasBradley\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\python.exe C:\Image_Mgmt_Workflows\OptimizeRasters\OptimizeRasters.py -config=C:\Image_Mgmt_Workflows\OptimizeRasters\Templates\Imagery_to_MRF_LERC_Test.xml -input=D:\Testing\Raster_Imagery\rm_data_for_doug\Sappi_23_29Dec19_Planet_TIFFs -output=D:\Testing\Raster_Imagery\rm_data_for_doug\Test_23_29Dec_MRF -rasterproxypath=D:\Testing\Raster_Imagery\rm_data_for_doug\Test_23_29Dec_Proxies\Test_23_29Dec_Proxies.csv

These same lines run when using the ArcMap 2.7 python.exe
Thanks for the assistance.

**Comment by Chamlika** [comment]
@DouglasBradley I'm unable to reproduce in Pro 2.4.3. Looks like an initialization issue, but shouldn't happen unless a custom launcher/start program is involved. 
@abhiataero  Could you check if you can reproduce, thanks!

**Comment by abhiataero** [comment]
@DouglasBradley  @Chamlika  i am not able to reproduce this, it might be due to the environment, 

@DouglasBradley  can you python exe which is from the installed location instead of clone, if you still get the issue we can do a screen share and check it out

**Comment by DouglasBradley** [comment]
> @DouglasBradley @Chamlika i am not able to reproduce this, it might be due to the environment,
> 
> @DouglasBradley can you python exe which is from the installed location instead of clone, if you still get the issue we can do a screen share and check it out

I thought of that when you mentioned the launcher/start program. I switch the python.exe to the ArcPro installed one and not the clone. The issue still persists, unfortunately.

**Comment by abhiataero** [comment]
@DouglasBradley  can we do a screen share and take a look at the issue, can you share your emailid so I  can send you an meeting invite

**Comment by DouglasBradley** [comment]
> @DouglasBradley can we do a screen share and take a look at the issue, can you share your emailid so I can send you an meeting invite

Hi, my email is douglas@swiftgeospatial.solutions

**Comment by abhiataero** [comment]
@DouglasBradley  the issue is happening due to the SolutionsLog folder missing from the location where Optimizeraster.py is there.

**Comment by DouglasBradley** [comment]
> @DouglasBradley the issue is happening due to the SolutionsLog folder missing from the location where Optimizeraster.py is there.

I have checked this and the folder is there.  
![Capture](https://user-images.githubusercontent.com/44017575/73358424-3be42300-42a7-11ea-9022-b94d884e6d83.JPG)

**Comment by abhiataero** [comment]
there was a logger module conflict so ti was failing. it was fixed by renaming the logger file
